### ISSUE TITLE
Bug: `WrapManifest` serialization failing for map-type wrapper

### ISSUE THREAD

**Issue by krisbitney** [polywrap/kotlin-client#14]
De/Serialization fails for the `wrap.info` wrap manifest found in the map-type test case wrapper. This is not related to serializing or deserializing the generic map type. Rather, it's an issue with serializing and deserializing the wrap manifest itself.

Stack trace
```
java.lang.IllegalArgumentException: Unable to parse WrapManifest: An unknown field for index -3
	at io.polywrap.core.wrap.formats.wrap01.WrapManifest01$Companion.deserialize-IoAF18A(WrapManifest01.kt:54)
	at core.WrapManifestTest.testSerializeAndDeserializeManifest(WrapManifestTest.kt:231)
	at core.WrapManifestTest.access$testSerializeAndDeserializeManifest(WrapManifestTest.kt:11)
	at core.WrapManifestTest$shouldSerializeAndDeserializeManifest_MapType$1.invokeSuspend(WrapManifestTest.kt:212)
```

**Comment by krisbitney** [comment]
This has been resolved
